grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localhost
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  adminPassword: admin

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.localhost
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

namespaceOverride: monitoring
