---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerconfigs.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: AlertmanagerConfig
    listKind: AlertmanagerConfigList
    plural: alertmanagerconfigs
    shortNames:
      - amcfg
    singular: alertmanagerconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: Alertmanager
    listKind: AlertmanagerList
    plural: alertmanagers
    shortNames:
      - am
    singular: alertmanager
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.version
          name: Version
          type: string
        - jsonPath: .spec.replicas
          name: Replicas
          type: integer
        - jsonPath: .status.availableReplicas
          name: Ready
          type: integer
        - jsonPath: .status.conditions[?(@.type == 'Reconciled')].status
          name: Reconciled
          type: string
        - jsonPath: .status.conditions[?(@.type == 'Available')].status
          name: Available
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.paused
          name: Paused
          priority: 1
          type: boolean
      name: v1
      served: true
      storage: true
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: PodMonitor
    listKind: PodMonitorList
    plural: podmonitors
    shortNames:
      - pmon
    singular: podmonitor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: probes.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: Probe
    listKind: ProbeList
    plural: probes
    shortNames:
      - prb
    singular: probe
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusagents.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: PrometheusAgent
    listKind: PrometheusAgentList
    plural: prometheusagents
    shortNames:
      - promagent
    singular: prometheusagent
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.version
          name: Version
          type: string
        - jsonPath: .spec.replicas
          name: Desired
          type: integer
        - jsonPath: .status.availableReplicas
          name: Ready
          type: integer
        - jsonPath: .status.conditions[?(@.type == 'Reconciled')].status
          name: Reconciled
          type: string
        - jsonPath: .status.conditions[?(@.type == 'Available')].status
          name: Available
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.paused
          name: Paused
          priority: 1
          type: boolean
      name: v1alpha1
      served: true
      storage: true
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.shards
          statusReplicasPath: .status.shards
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    shortNames:
      - prom
    singular: prometheus
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.version
          name: Version
          type: string
        - jsonPath: .spec.replicas
          name: Desired
          type: integer
        - jsonPath: .status.availableReplicas
          name: Ready
          type: integer
        - jsonPath: .status.conditions[?(@.type == 'Reconciled')].status
          name: Reconciled
          type: string
        - jsonPath: .status.conditions[?(@.type == 'Available')].status
          name: Available
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.paused
          name: Paused
          priority: 1
          type: boolean
      name: v1
      served: true
      storage: true
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.shards
          statusReplicasPath: .status.shards
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusrules.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: PrometheusRule
    listKind: PrometheusRuleList
    plural: prometheusrules
    shortNames:
      - promrule
    singular: prometheusrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scrapeconfigs.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: ScrapeConfig
    listKind: ScrapeConfigList
    plural: scrapeconfigs
    shortNames:
      - scfg
    singular: scrapeconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: ServiceMonitor
    listKind: ServiceMonitorList
    plural: servicemonitors
    shortNames:
      - smon
    singular: servicemonitor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: thanosrulers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    categories:
      - prometheus-operator
    kind: ThanosRuler
    listKind: ThanosRulerList
    plural: thanosrulers
    shortNames:
      - ruler
    singular: thanosruler
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.version
          name: Version
          type: string
        - jsonPath: .spec.replicas
          name: Replicas
          type: integer
        - jsonPath: .status.availableReplicas
          name: Ready
          type: integer
        - jsonPath: .status.conditions[?(@.type == 'Reconciled')].status
          name: Reconciled
          type: string
        - jsonPath: .status.conditions[?(@.type == 'Available')].status
          name: Available
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.paused
          name: Paused
          priority: 1
          type: boolean
      name: v1
      served: true
      storage: true
      subresources:
        status: {}
